name: Mocka CI
on: [push]
jobs:

  build:
    name: Run Linting and Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Run linting with Revive
      uses: morphy2k/revive-action@v1.2.0
      with:
        config: revive.toml

    - name: Run tests
      run: go test ./... -v -cover
